# Ensure asdf core is installed

---

- name: Ensure asdf dependencies are installed
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  become: true
  loop:
    - curl
    - git

- name: Ensure asdf core is installed
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    single_branch: true
    version: '{{ asdf_version }}'

- name: Ensure asdf is configured in bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    create: true
    mode: 0644
    line: '{{ item }}'
  loop:
    - . $HOME/.asdf/asdf.sh
    - . $HOME/.asdf/completions/asdf.bash

- name: Ensure bashrc is sourced
  ansible.builtin.shell:
    cmd: source ~/.bashrc
  changed_when: false

- name: Ensure legacy version file is configured in asdfrc
  ansible.builtin.lineinfile:
    path: ~/.asdfrc
    create: true
    mode: 0644
    line: legacy_version_file = yes
