# Ensure asdf plugins are configured

---

- name: Retrieve list of installed asdf plugins
  ansible.builtin.command:
    cmd: asdf plugin list
  changed_when: false
  register: asdf_installed_plugins

- name: Ensure asdf plugins are installed
  ansible.builtin.command:
    cmd: 'asdf plugin add {{ item.name }} {{ item.url if item.url is defined }}'
  when: item.state | default('present') != 'absent' and item.name not in asdf_installed_plugins.stdout
  loop: '{{ asdf_plugins }}'

- name: Ensure asdf plugins set to absent are uninstalled
  ansible.builtin.command:
    cmd: 'asdf plugin remove {{ item.name }}'
  when: item.state | default('present') == 'absent' and item.name in asdf_installed_plugins.stdout
  loop: '{{ asdf_plugins }}'

- name: Retrieve updated list of installed asdf plugins
  ansible.builtin.command:
    cmd: asdf plugin list
  changed_when: false
  register: asdf_installed_plugins

